$(":input, textarea, select, input").prop("readonly", true).attr("disabled", true).addClass("bg-gray/5 text-black/60")
$(".js-xaside-maximize-menu").prop("readonly", false).attr("disabled", false).removeClass("bg-gray/5 text-black/60")
import { generate_nft } from "./nft.js"

const modalButton = $(".js-cert-sign-blockchain-modal")
if (modalButton.attr("data-reciver") === "1" && modalButton.attr("data-creator") === "1") {
  modalButton.prop("disabled", false).addClass("btn-neutral text-white")
  $(".js-cert-modal-tooltip").removeClass("tooltip")
}

$(".js-cert-sign-blockchain-modal").on("click", function () {
  // $(this).hide()
  generate_nft(GLOBAL_AUTH_USER.id, "js-cert-node", $(".js-cert-token").html(), "certificate", "NFT Certificate", "Generated by Bnic.io")
})

$(function () {
  $("field.js-element input, field.js-element textarea, .js_additional_input").each(function () {
    if (typeof $(this).attr("placeholder") !== "undefined") {
      $(this).before(
        $("<div>", {
          text: $(this).attr("placeholder"),
        })
      )
    }
    //
  })
})

console.log($(".file_upload_url"))

let filepond = $("<input>", {
  type: "file",
  class: "generated_file_pond w-full block rounded-lg ",
  value: $(".file_upload_url").val(),
})
console.log(filepond)



$(".file_upload_url").before(filepond)
import * as FilePond from "filepond"
import FilePondPluginImagePreview from "filepond-plugin-image-preview"
import FilePondPluginPdfPreview from "filepond-plugin-pdf-preview"
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css"
FilePond.registerPlugin(FilePondPluginImagePreview)
FilePond.registerPlugin(FilePondPluginPdfPreview)
const inputElement = document.querySelector(".generated_file_pond")
const pond = FilePond.create(inputElement, {})
pond.addFile($(".file_upload_url").val())
pond.setOptions({
  allowRevert: false,
  allowAdd: false,
  readOnly: true,
})



