$(":input, textarea, select, input").prop("readonly", true).attr("disabled", true).addClass("bg-gray/5 text-black/60")
$(".js-xaside-maximize-menu").prop("readonly", false).attr("disabled", false).removeClass("bg-gray/5 text-black/60")
import { generate_nft } from "./nft.js"

const modalButton = $(".js-cert-sign-blockchain-modal")
if (modalButton.attr("data-reciver") === "1" && modalButton.attr("data-creator") === "1") {
    modalButton.prop("disabled", false).addClass("btn-neutral text-white")
    $(".js-cert-modal-tooltip").removeClass("tooltip")
}

modalButton.on("click", function () {
    generate_nft(GLOBAL_AUTH_USER.id, "js-cert-node", $(".js-cert-token").html(), "certificate", "NFT Certificate", "Generated by Bnic.io")
})
