import { generate_nft } from "./nft.js"
$(() => {
    $(".js-btn-signchain-submit").on("click", function () {
        $(".js-nft-box").removeClass("border")
        generate_nft($(".js-user_id").val(), "js-nft-box", $(".js-span-token").html(), "profile", "NFT Profile", "Generated by Bnic.io", null, true)
    })
})

//edit profile
$(".js_profile_picture").on("click", () => {
    edit_profile_picture.showModal()
})

import * as FilePond from "filepond"
import FilePondPluginImagePreview from "filepond-plugin-image-preview"
import FilePondPluginPdfPreview from "filepond-plugin-pdf-preview"
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css"
FilePond.registerPlugin(FilePondPluginImagePreview)
FilePond.registerPlugin(FilePondPluginPdfPreview)
const inputElement = document.querySelector(".js_profile_picture_file_input")
const pond = FilePond.create(inputElement, {
    server: {
        url: "/api/filepond", // Update this to your Laravel API endpoint
        process: "/process",
        revert: "/revert",
        restore: "/restore",
        load: "/load",
    },
})
let image_field = null

pond.on("processfile", (error, file) => {
    if (error) {
        console.error("File processing failed:", error)
        return
    }
    const response = JSON.parse(file.serverId)
    image_field = $("<input>")
        .attr({
            type: "hidden",
            class: "js_image_address",
            value: response.id,
        })
        .appendTo("body")
    $(".js_update_picture").removeClass("btn-disabled opacity-50")
    console.log(image_field.val())
})

$(".js_update_picture").on("click", () => {
    axios
        .post(route("api.update"), {
            id: GLOBAL_AUTH_USER.id,
            profile_picture: image_field.val(),
        })
        .then(() => window.location.reload())
})


$('.js_pay_fee_toggle').on('change',function(){
    $('.js_pay_fee_toggle').prop('checked',$(this).prop('checked'))
})