import { generate_nft } from "./nft.js"
$(() => {
    $(".js-btn-signchain-submit").on("click", function () {
        $(".js-nft-box").removeClass("border")
        generate_nft($(".js-user_id").val(), "js-nft-box", $(".js-span-token").html(), "profile", "NFT Profile", "Generated by Bnic.io", null, true)
    })
})
