import { generate_nft } from "./nft"

$(() => {
  $(".btn_generate_petition_nft").on("click", function () {
    let random = Math.floor(Math.random() * (9e12 - 1e12) + 1e12)
    $(".btn_generate_petition_nft").css("opacity", 0)
    generate_nft(GLOBAL_AUTH_USER.id, "js_petition_dom", random, "petition", "NFT petition", "Generated by Bnic.io", null, false, {
      type: "petition",
      petition_id: $(".js_petition_id").val(),
    })
  })
})
